apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: focusflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cr.yandex/crp1ghkks5e8qc0ftr95/frontend:5be847223334b98f48736eb5697a26d1b04145f3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
