apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: focusflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cr.yandex/crp1ghkks5e8qc0ftr95/frontend:c6aa77482c550230820348733286d7ba0e272465
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
